services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: agentsphere-backend
    # volumes:
    #   - ./backend/test_runs:/app/test_runs
    #   - ./backend/authfiles/db.json:/app/authfiles/db.json
    #   - /var/run/docker.sock:/var/run/docker.sock
    volumes:
      - ./backend/test_runs:/app/test_runs
      - ./backend/authfiles/db.json:/app/authfiles/db.json
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    restart: unless-stopped

  frontend:
    build: ./frontend1
    ports:
      - "3000:80"
    container_name: agentsphere-frontend
    depends_on:
      - backend
    restart: unless-stopped

  agent-runner:
    build:
      context: ./backend
      dockerfile: dockerfile.runner
    image: agent-runner:latest
    profiles:
      - runner
    network_mode: bridge